### ISSUE TITLE
Missing space after permissions for first entry

### ISSUE THREAD

**Issue by rathsky** [trapd00r/ls--#57] opened 2017-09-17 09:29 UTC
Regardless of ls++'s options or folder content, the first line is always missing a space for me.

IOW, ls++ prints eg. "drwxr-xr-x\<one space>▏" instead of "drwxr-xr-x\<two spaces>|" as for the remaining lines (markup filtered).

Using updated Arch Linux.

**Comment by tuncenator** [comment] 2018-02-12 11:14
Can confirm [Arch]
```
tunc@BEER ~/.i3/i3-easyfocus$ lsd                                                                                                   master   12/02 [14:06] 
total 92K
▕ drwxr-xr-x▏tunc:users│<  sec │   4K│src
▕ -rw-r--r-- ▏tunc:users│35 sec │  35K│LICENSE
▕ -rw-r--r-- ▏tunc:users│35 sec │ 564B│Makefile
▕ -rw-r--r-- ▏tunc:users│35 sec │ 1.2K│README.md
▕ -rwxr-xr-x ▏tunc:users│<  sec │  31K│i3-easyfocus
▕ -rw-r--r-- ▏tunc:users│35 sec │  11K│screenshot.png
```

**Comment by trapd00r** [comment] 2019-03-17 11:00
Is this still an issue? I can not reproduce.

**Comment by rathsky** [comment] 2019-03-17 11:37
Yes, same as before. Also I now get "â" instead of | as separator.

**Comment by trapd00r** [comment] 2019-03-17 12:43
Is this with latest version from git? (0.60).
What's your locale?

**Comment by trapd00r** [comment] 2019-03-17 13:02
[see this commit regarding ls++.conf](https://github.com/trapd00r/ls--/commit/c9096831b15d00ce1f93e6308fd1ebf310155433#diff-df91f328f46938f7bb17c764a1649d1fR9).

You can try to add

`
use utf8;
use open qw(:utf8 :std);
`
on the top of your own ls++.conf

**Comment by rathsky** [comment] 2019-03-17 13:11
It's de_DE.utf8, the two lines don't have an effect. Version is latest git, ie. now 0.60.

BTW, the makefile fails with ~/.ls++.conf present on Arch, presumably as it tries to break out of the isolated build environment.

**Comment by trapd00r** [comment] 2019-03-17 13:20
Try this:

`DEBUG=1 ls++`

**Comment by rathsky** [comment] 2019-03-17 13:22
Ah, about the conf: It places a ~/.ls++.conf on install, but I already had a higher priority ~/.config/ls++/ls++.conf

**Comment by trapd00r** [comment] 2019-03-17 13:24
Yeah, I can see now that the config file locations will need a stricter checkup. I'll get to it.
In the meantime, can you add those utf8 lines to the config file that ls++ actualy uses and see if it makes any difference? It should - I had the same issue myself after a recent perl upgrade.

**Comment by rathsky** [comment] 2019-03-17 13:29
So… moved the newly installed ~/.ls++.conf (with the utf8 lines) to ~/.config/ls++/ls++.conf, deleting the old one:

| is back, but the space is still missing.

(I think it would be good to throw an error if more than one config is found.)

**Comment by rathsky** [comment] 2019-03-17 13:32
DEBUG=1 ls++ just prints

>Can't locate ./ls++.conf at /usr/bin/vendor_perl/ls++ line 624.

**Comment by trapd00r** [comment] 2019-03-17 13:39
I've simplified the config file locations by allowing just $HOME/.ls++.conf.

Regarding the space. I still can not reproduce, but I'll dig in looking for an culprit. (Also using arch...)

**Comment by trapd00r** [comment] 2019-03-17 13:45
What's your $TERM?

**Comment by rathsky** [comment] 2019-03-17 13:50
Yeah, I was just going to ask which shell are you using… I now noticed that the | are printed correctly (and without spacing to the preceding character) on bash. Usually I'm on zsh. Might just be some variable thing, though:

![ls++](https://user-images.githubusercontent.com/887320/54492032-6a415580-48c3-11e9-8a9d-4bfcab3ff46a.png)

… started via urxvt -e bash/zsh. Both first lines yield the same string if c&p to an extern program… also, while bash has the correct spacing.

**Comment by rathsky** [comment] 2019-03-17 13:55
Uhm, ok: The first lines are identical, the *following* ones aren't. zsh prints an additional space between after the permissions and the | there.

zsh:
>▕ drwx------▏38 min │  60B│systemd-private-blabla
>▕ drwx------ ▏38 min │  60B│systemd-private-blabla
>▕ drwx------ ▏21 sec │  60B│tmux-1000
>▕ -rw------- ▏38 min │ 159B│serverauth.blabla

bash:
>▕ drwx------▏38 min │  60B│systemd-private-blabla
>▕ drwx------▏38 min │  60B│systemd-private-blabla
>▕ drwx------▏19 sec │  60B│tmux-1000
>▕ -rw-------▏38 min │ 159B│serverauth.blabla

**Comment by trapd00r** [comment] 2019-03-17 13:55
This is so weird. I am using zsh as well, but:
![weird](https://user-images.githubusercontent.com/43331/54492198-a5905400-48c4-11e9-8b67-97d3df90c5c4.png)

**Comment by trapd00r** [comment] 2019-03-17 13:56
Do you set $TERM anywhere in either your zsh or bash configuration?

**Comment by rathsky** [comment] 2019-03-17 14:00
Yes, forgot where but

* $TERM is screen-256color on tmux

* $TERM is rxvt-256color in urxvt-only (screenshot)

* $TERMTYPE is 16 in either (dunno why I did that)

**Comment by trapd00r** [comment] 2019-03-17 14:06
I've tried all of those combinations, still can not reproduce. :rofl: 
Can you try my [ls++.conf](https://raw.githubusercontent.com/trapd00r/configs/master/ls%2B%2B/ls%2B%2B.conf) ?

**Comment by rathsky** [comment] 2019-03-17 14:12
No change with that, but I think I got it now… something from a prior LS_COLORS. Replaced with the current version, now it seems fine. 😅

**Comment by trapd00r** [comment] 2019-03-17 14:15
Hm. Interesting.

**Comment by trapd00r** [comment] 2019-03-17 14:17
Perhaps something with the di key in LS_COLORS - since dirs always lists first. Assuming you're not sure you had the issue in dirs with no directories in them.

**Comment by trapd00r** [comment] 2019-03-18 07:36
Closing this now as the issue seems resolved.

**Closed by trapd00r** 2019-03-18 07:36 UTC
